"""datetime today

Revision ID: e18f8e1e94c0
Revises: f357de839cec
Create Date: 2021-01-30 14:22:10.389915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18f8e1e94c0'
down_revision = 'f357de839cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updated', sa.Column('today', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_updated_today'), 'updated', ['today'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_updated_today'), table_name='updated')
    op.drop_column('updated', 'today')
    # ### end Alembic commands ###
