"""updatet activities

Revision ID: f357de839cec
Revises: 
Create Date: 2021-01-30 13:41:19.586964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f357de839cec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('updated',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=125), nullable=True),
    sa.Column('bumbal_id', sa.String(length=20), nullable=True),
    sa.Column('updated_by', sa.String(length=5), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_updated_bumbal_id'), 'updated', ['bumbal_id'], unique=False)
    op.create_index(op.f('ix_updated_reference'), 'updated', ['reference'], unique=False)
    op.create_index(op.f('ix_updated_timestamp'), 'updated', ['timestamp'], unique=False)
    op.create_index(op.f('ix_updated_updated_by'), 'updated', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_updated_updated_by'), table_name='updated')
    op.drop_index(op.f('ix_updated_timestamp'), table_name='updated')
    op.drop_index(op.f('ix_updated_reference'), table_name='updated')
    op.drop_index(op.f('ix_updated_bumbal_id'), table_name='updated')
    op.drop_table('updated')
    # ### end Alembic commands ###
